{ hmHelpers }:
{ config, lib, pkgs, ... }:

let
  cfg = config.services.tatara-os-vm;
  inherit (lib) mkEnableOption mkOption types mkIf literalExpression;
  isDarwin = pkgs.stdenv.isDarwin;

  # Root directory for everything this VM owns.
  vmRoot = "${config.home.homeDirectory}/.local/share/tatara-os/${cfg.hostname}";

  # Author the system + vm Lisp form on the fly so users who just want the
  # defaults don't need to hand-write one. If `systemFile` is set, we use
  # that instead.
  generatedSystemLisp = pkgs.writeText "tatara-os-${cfg.hostname}.lisp" ''
    ; auto-generated by home-manager — edit via
    ; `services.tatara-os-vm` options.

    (defsystem
      :hostname "${cfg.hostname}"
      :system   "${cfg.system}"
      :services (${lib.concatMapStringsSep "\n                 " (svc: ''
        (:name "${svc.name}" :exec "${svc.exec}" :enable #t)
      '') cfg.services}))

    (defvm
      :name       "${cfg.hostname}"
      :cpus       ${toString cfg.cpus}
      :memory-mib ${toString cfg.memoryMib}
      :hypervisor (:kind "Vfkit")
      :kernel     (:kind "Bridge" :attr_path "linuxPackages.kernel")
      :rootfs     (:kind "Bridge" :attr_path "placeholder")
      :network    (:kind "Nat")
      :cmdline    ("console=hvc0" "init=/bin/tatara-init"))
  '';

  resolvedSystemFile =
    if cfg.systemFile != null then cfg.systemFile else generatedSystemLisp;

  # Activation script: regenerate the boot artifact tree + pre-realize the
  # initrd derivation in /nix/store. The boot.sh launcher it emits is what
  # we point launchd / systemd-user at.
  activationScript = ''
    ${pkgs.coreutils}/bin/mkdir -p ${vmRoot}
    ${cfg.package}/bin/tatara-boot-gen \
      ${resolvedSystemFile} \
      ${vmRoot} \
      ${lib.optionalString (!cfg.busybox) "--no-busybox"} \
      ${lib.optionalString (!cfg.verbose) "--quiet"}
    # Pre-realize the initrd — first build is slow, cached after that.
    ${lib.optionalString cfg.prebuildInitrd ''
      ${pkgs.nix}/bin/nix build \
        -f ${vmRoot}/initrd.nix \
        --no-link --print-out-paths \
        > ${vmRoot}/.initrd-store-path 2>${vmRoot}/.initrd-build.log || true
    ''}
  '';
in
{
  options.services.tatara-os-vm = {
    enable = mkEnableOption "tatara-os VM — a Darwin-hosted Linux guest whose init is `tatara-init` (PID 1), authored in tatara-lisp";

    package = mkOption {
      type = types.package;
      description = "The tatara-vm flake output exposing `tatara-boot-gen`. Override when pinning.";
      example = literalExpression "inputs.tatara.packages.\${pkgs.system}.boot-gen";
    };

    terreiroPackage = mkOption {
      type = types.nullOr types.package;
      default = null;
      description = ''
        Optional `tatara-terreiro` CLI package. When non-null, installed
        into the HM user profile alongside tatara-boot-gen. Commands:
        new / id / seal / load / compile / eval / realize.
      '';
      example = literalExpression "inputs.tatara.packages.\${pkgs.system}.terreiro";
    };

    hostname = mkOption {
      type = types.str;
      default = "plex";
      description = "Guest hostname (used to derive file paths + derivation names).";
    };

    system = mkOption {
      type = types.str;
      default = "aarch64-linux";
      description = "Guest system (for the kernel + rootfs cross-build target).";
    };

    cpus = mkOption {
      type = types.int;
      default = 2;
      description = "vCPU count for the guest.";
    };

    memoryMib = mkOption {
      type = types.int;
      default = 1024;
      description = "Guest memory in MiB.";
    };

    services = mkOption {
      type = types.listOf (types.submodule {
        options = {
          name = mkOption { type = types.str; };
          exec = mkOption { type = types.str; };
        };
      });
      default = [];
      description = ''
        Supervised services for tatara-init (PID 1) inside the guest.
        Becomes the `:services` list in the generated (definit …) form.
      '';
      example = literalExpression ''[
        { name = "sshd"; exec = "/bin/sshd -D -f /etc/ssh/sshd_config"; }
      ]'';
    };

    sshAuthorizedKeys = mkOption {
      type = types.listOf types.str;
      default = [];
      description = ''
        OpenSSH public keys authorized for the guest. When non-empty, the
        activation script writes them to `$vmRoot/authorized_keys`, and the
        (work-in-progress) initrd builder will bake them into
        `/etc/ssh/authorized_keys` inside the guest.
      '';
    };

    sshPort = mkOption {
      type = types.int;
      default = 2222;
      description = "Port the guest's sshd listens on (forwarded through vfkit).";
    };

    busybox = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Include busybox + applet symlinks in the initrd. Set false when
        building on a host that can't produce Linux busybox (e.g. a naive
        Darwin dev flow without linux-builder).
      '';
    };

    prebuildInitrd = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Run `nix build -f initrd.nix` during home-manager activation so the
        first boot is not slow. Requires `linux-builder` on Darwin hosts.
      '';
    };

    systemFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = ''
        Optional path to a hand-written `.lisp` file containing the
        (defsystem …) + (defvm …) forms. Overrides the auto-generated
        form built from this module's options.
      '';
    };

    verbose = mkOption {
      type = types.bool;
      default = false;
      description = "Show the Nord-themed UX stream during activation.";
    };
  };

  config = mkIf cfg.enable {
    home.packages = [
      cfg.package
      pkgs.vfkit
    ] ++ lib.optional (cfg.terreiroPackage != null) cfg.terreiroPackage;

    # Drop authorized_keys + a launcher into the VM root at activation
    # time. The launcher is what a launchd agent (future) will exec.
    # Uses home-manager's native DAG API (`lib.hm.dag.entryAfter`) —
    # `writeBoundary` is HM's own marker that guarantees home files are
    # written before our hook runs.
    home.activation.tataraOsVm = lib.hm.dag.entryAfter [ "writeBoundary" ] (
      activationScript
      + lib.optionalString (cfg.sshAuthorizedKeys != []) ''
        ${pkgs.coreutils}/bin/mkdir -p ${vmRoot}
        ${pkgs.coreutils}/bin/cat > ${vmRoot}/authorized_keys <<'TATARA_AUTH_KEYS_EOF'
        ${lib.concatStringsSep "\n" cfg.sshAuthorizedKeys}
        TATARA_AUTH_KEYS_EOF
      ''
      + ''
        # Write a tiny boot launcher the user can invoke directly, or that
        # a launchd agent can exec. Lives at $vmRoot/launch.sh.
        ${pkgs.coreutils}/bin/cat > ${vmRoot}/launch.sh <<'TATARA_LAUNCH_EOF'
        #!/bin/sh
        set -eu
        VM_ROOT="${vmRoot}"
        KERNEL=$(${pkgs.nix}/bin/nix build -f "$VM_ROOT/kernel.nix" --no-link --print-out-paths)/bzImage
        INITRD=$(${pkgs.nix}/bin/nix build -f "$VM_ROOT/initrd.nix" --no-link --print-out-paths)/initrd.cpio.gz
        # Splice the real paths into vm.json before handing it to vfkit.
        ${pkgs.jq}/bin/jq --arg kernel "$KERNEL" --arg initrd "$INITRD" \
          '.kernel = $kernel | .initrd = $initrd | (.devices[] | select(.device == "virtio-blk") | .image) = $initrd' \
          "$VM_ROOT/vm.json" > "$VM_ROOT/vm-resolved.json"
        exec ${pkgs.vfkit}/bin/vfkit --config "$VM_ROOT/vm-resolved.json"
        TATARA_LAUNCH_EOF
        ${pkgs.coreutils}/bin/chmod +x ${vmRoot}/launch.sh
      ''
    );
  };
}
