//! Compose a tatara-os `SystemConfig` + a tatara-init binary path into a
//! complete bootable VM manifest — kernel derivation + initrd derivation +
//! `VmSpec` ready to hand to `VfkitEmitter`.
//!
//! The goal: one call takes everything a user has typed in Lisp
//! (`(defsystem …)`, `(definit …)`, `(defvm …)`) and gives back the
//! on-disk artifacts that `vfkit --config vm.json` can boot.

use tatara_nix::derivation::{BridgeTarget, Derivation, Outputs, Source};
use tatara_os::SystemConfig;

use crate::config::{GuestKernel, GuestRootfs, Hypervisor, VmSpec};
use crate::rootfs::{InitrdFile, LinuxRootfs};

/// The full set of on-disk-buildable artifacts for one VM boot.
pub struct BootManifest {
    /// Kernel derivation — bridged to `linuxPackages.kernel` by default, or
    /// whatever the caller's `SystemConfig::kernel` pointed at.
    pub kernel: Derivation,
    /// Initrd derivation — our rootfs.cpio.gz with tatara-init + init.lisp.
    pub initrd: Derivation,
    /// The VM manifest, wired to those two derivations. Use
    /// [`VfkitEmitter::with_kernel_path`] / `with_rootfs_path` to substitute
    /// the realized /nix/store paths.
    pub vm: VmSpec,
}

/// Build a `BootManifest` from a tatara-os system configuration.
///
/// - `sys` — the tatara-os `SystemConfig` (authored with `(defsystem …)`).
/// - `init_binary_path` — `/nix/store` path of the `tatara-init` binary. In
///   practice you pass the realization of `tatara.packages.${system}.init`.
/// - `vm` — VM-shape overrides (cpus, memory, network, shares). If `None`,
///   uses `VmSpec::plex_default(<hostname>)` with sensible defaults.
pub fn compose(
    sys: &SystemConfig,
    init_binary_path: impl Into<String>,
    vm: Option<VmSpec>,
) -> BootManifest {
    let init_path = init_binary_path.into();
    let hostname = sys.hostname.clone();

    // 1. Kernel — honor whatever the SystemConfig said.
    let kernel_attr = match &sys.kernel {
        tatara_os::KernelSpec::Bridge { attr_path } => attr_path.clone(),
        tatara_os::KernelSpec::Package { name } => name.clone(),
        tatara_os::KernelSpec::Custom { .. } => "linuxPackages.kernel".into(),
    };
    let kernel = Derivation {
        name: format!("kernel-{}", sanitize(&hostname)),
        version: None,
        inputs: vec![],
        source: Source::default(),
        builder: Default::default(),
        outputs: Outputs::default(),
        env: vec![],
        sandbox: Default::default(),
        bridge: Some(BridgeTarget::nixpkgs(kernel_attr)),
        nix_expr: None,
    };

    // 2. Initrd — tatara-init + init.lisp synthesized from services.
    let init_config = synthesize_init_config(sys);
    let mut rootfs = LinuxRootfs::new(&init_path, init_config)
        .with_name(format!("initrd-{}", sanitize(&hostname)));
    // /etc/hostname is useful inside the guest.
    rootfs = rootfs.with_file("/etc/hostname", format!("{}\n", sys.hostname));
    // /etc files the user declared.
    for f in &sys.environment.etc_files {
        let path = if f.path.starts_with('/') {
            f.path.clone()
        } else {
            format!("/etc/{}", f.path)
        };
        rootfs.extra_files.push(InitrdFile {
            path,
            content: crate::rootfs::InitrdContent::Inline(f.content.clone()),
            mode: 0o644,
        });
    }
    let initrd = rootfs.derivation();

    // 3. VmSpec — default or user-provided, but always pointed at our
    // kernel/initrd derivations via the Bridge mechanism (fleshed out by
    // `VfkitEmitter::with_*_path` at emit time when the caller has the
    // realized store paths on hand).
    let mut vm = vm.unwrap_or_else(|| VmSpec::plex_default(&hostname));
    vm.hypervisor = Hypervisor::Vfkit;
    vm.kernel = GuestKernel::Custom {
        derivation: kernel.clone(),
    };
    vm.rootfs = GuestRootfs::Image {
        derivation: initrd.clone(),
    };
    vm.initrd = Some(initrd.clone());
    if !vm.cmdline.iter().any(|s| s.contains("init=/bin/tatara-init")) {
        vm.cmdline.push("init=/bin/tatara-init".into());
    }

    BootManifest {
        kernel,
        initrd,
        vm,
    }
}

/// Derive the init.lisp content from the system's service list. Mirrors the
/// service shape tatara-init expects: `(definit :services (...))`.
fn synthesize_init_config(sys: &SystemConfig) -> String {
    let mut s = format!("; auto-generated by tatara-vm::boot for '{}'\n", sys.hostname);
    s.push_str(&format!("(definit\n  :name \"{}-boot\"\n", sys.hostname));
    if sys.services.is_empty() {
        s.push_str("  :services ())\n");
        return s;
    }
    s.push_str("  :services (\n");
    for svc in &sys.services {
        let enable = if svc.enable { "#t" } else { "#f" };
        s.push_str(&format!(
            "    (:name \"{}\" :exec \"{}\" :enable {})\n",
            svc.name,
            svc.exec.replace('"', "\\\""),
            enable
        ));
    }
    s.push_str("  ))\n");
    s
}

fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c
            } else {
                '-'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sys() -> SystemConfig {
        SystemConfig {
            hostname: "plex".into(),
            system: "aarch64-linux".into(),
            kernel: tatara_os::KernelSpec::Bridge {
                attr_path: "linuxPackages.kernel".into(),
            },
            bootloader: Default::default(),
            init: tatara_os::InitSystem::Tatara,
            services: vec![
                tatara_os::ServiceSpec {
                    name: "demo".into(),
                    exec: "/bin/busybox sh -c 'echo tatara'".into(),
                    enable: true,
                    extra: vec![],
                    package_refs: vec![],
                },
                tatara_os::ServiceSpec {
                    name: "disabled-one".into(),
                    exec: "/bin/disabled".into(),
                    enable: false,
                    extra: vec![],
                    package_refs: vec![],
                },
            ],
            users: vec![],
            filesystems: vec![],
            environment: Default::default(),
            packages: vec![],
        }
    }

    #[test]
    fn compose_produces_kernel_initrd_and_vm() {
        let bm = compose(&sys(), "/nix/store/xxx-tatara-init/bin/tatara-init", None);
        assert_eq!(bm.kernel.name, "kernel-plex");
        assert!(bm.kernel.bridge.is_some());
        assert_eq!(bm.initrd.name, "initrd-plex");
        assert!(bm.initrd.nix_expr.is_some());
        assert_eq!(bm.vm.name, "plex");
    }

    #[test]
    fn cmdline_gets_tatara_init_appended() {
        let mut custom = VmSpec::plex_default("plex");
        custom.cmdline = vec!["console=hvc0".into()]; // no init=
        let bm = compose(&sys(), "/nix/store/xxx-init/bin/tatara-init", Some(custom));
        assert!(bm
            .vm
            .cmdline
            .iter()
            .any(|s| s.contains("init=/bin/tatara-init")));
    }

    #[test]
    fn init_lisp_lists_enabled_services_only_as_enabled() {
        let bm = compose(&sys(), "/nix/store/xxx-init/bin/tatara-init", None);
        let expr = bm.initrd.nix_expr.unwrap();
        assert!(expr.contains("(:name \"demo\" :exec"));
        assert!(expr.contains(":enable #t"));
        assert!(expr.contains("(:name \"disabled-one\" :exec"));
        assert!(expr.contains(":enable #f"));
    }

    #[test]
    fn etc_hostname_is_included() {
        let bm = compose(&sys(), "/nix/store/xxx-init/bin/tatara-init", None);
        let expr = bm.initrd.nix_expr.unwrap();
        assert!(expr.contains("root/etc/hostname"));
        assert!(expr.contains("plex"));
    }

    #[test]
    fn custom_kernel_package_propagates_to_bridge() {
        let mut s = sys();
        s.kernel = tatara_os::KernelSpec::Bridge {
            attr_path: "linuxPackages_latest.kernel".into(),
        };
        let bm = compose(&s, "/nix/store/x/bin/tatara-init", None);
        assert_eq!(
            bm.kernel.bridge.unwrap().attr_path,
            "linuxPackages_latest.kernel"
        );
    }
}
